### ISSUE TITLE
atr format doesn't seem to be documented

### ISSUE THREAD

**Issue by Moth-Tolias** [Enemby/Auteur#1]
hullo! interesting concept you've got here. i can't seem to find any documentation on the atr format, though? also, i'm not quite sure what's meant by placing atr files with their assets - does it matter to the atr file where files are placed?

best regards,
susan

**Comment by Enemby** [comment]
Hi! .ATR files are simply metadata that should be placed in the same folder as your assets. Inside the file is details of the author and a list of files it applies to, which is relative to its directory. They're plaintext, and you can see an example in "Enemby.atr" in the assets folder.

So basically, if you place an .ATR file in a folder, the Auteur program will pick it up and list it in its final contributor credits.txt. Currently its file list is not implemented in Auteur, but they are built so they work in the future. 

Eventually I'd like to add a mode that uses this data to make informed credits lists with work performed in the project, but this will probably happen quite a bit later.
